ibm-mas/gitops

- applications/ibm-mas-suite-app-config/templates/01-ibm-manage_jms_manage_additional_server_config_secrets.yaml
- applications/ibm-mas-suite-app-config/templates/01-ibm-manage_snojms_manage_additional_server_config_secrets.yaml
- applications/ibm-mas-suite-app-config/templates/01-ibm-mas_Suite_App_workspace.yaml
- applications/ibm-mas-suite-app-install/templates/02-ibm-mas_customsccinit.yaml
- applications/ibm-mas-suite-app-install/templates/06-ibm-mas_customscc.yaml
> [minor][MASCORE-763] Include defaultJMS

- applications/ibm-mas-suite-app-config/templates/01-ibm-mas_Suite_App_workspace.yaml
- applications/ibm-mas-suite-app-install/templates/05-ibm-mas_Suite_App_Install.yaml
> [patch] app spec changes

- applications/ibm-dro/Chart.yaml
- applications/ibm-dro/README.md
- applications/ibm-dro/templates/00-dro_Namespace.yaml
- applications/ibm-dro/templates/01-dro_OperatorGroup.yaml
- applications/ibm-dro/templates/02-dro-api-token_Secret.yaml
- applications/ibm-dro/templates/02-dro-pull_Secret.yaml
- applications/ibm-dro/templates/03-imo_Subscription.yaml
- applications/ibm-dro/templates/04-dro_Subscription.yaml
- applications/ibm-dro/templates/05-rmo_Subscription.yaml
- applications/ibm-dro/templates/06-marketplaceconfig_Marketplaceconfig.yaml
- applications/ibm-dro/templates/07-dro-api-token_Secret.yaml
- applications/ibm-dro/values.yaml
- applications/ibm-mas-configs/templates/01-dro-api-token_Secret.yaml
- applications/ibm-mas-configs/templates/03-ibm-mas_BasCfg.yaml
Adds DRO app so we can deploy DRO. Also updates the bascfg so it will point to the DRO instance rather than use suds
> Add dro app and dro config

- applications/020-ibm-dro/templates/08-postsync-update-sm_Job.yaml
The dro url comes from the route of dro. This was missing from the dro secret
> Add missing dro_url to dro secret

- applications/130-ibm-db2u-jdbc-config/templates/00-presync-create-db2-user_Job.yaml
This includes a small fix commit that was missed in the previous PR: https://github.com/ibm-mas/gitops/pull/40
> Execute "user exists check" command on correct db2u pod (add missed commit)

- root-applications/ibm-mas-cluster-root/templates/000-ibm-operator-catalog-app.yaml
- root-applications/ibm-mas-cluster-root/templates/010-ibm-redhat-cert-manager-app.yaml
- root-applications/ibm-mas-cluster-root/templates/020-ibm-dro-app.yaml
- root-applications/ibm-mas-cluster-root/templates/040-cis-compliance-app.yaml
- root-applications/ibm-mas-cluster-root/templates/050-nvidia-gpu-operator-app.yaml
- root-applications/ibm-mas-cluster-root/templates/060-ibm-db2u-app.yaml
- root-applications/ibm-mas-instance-root/templates/100-ibm-sls-app.yaml
- root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
- root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml
- root-applications/ibm-mas-instance-root/templates/220-ibm-mas-workspace.yaml
Add annotation for slack notification on the applications
> [patch] add annotation for notification

- applications/130-ibm-mas-bas-config/templates/03-ibm-mas_BasCfg.yaml
add support for BasCfg segmentKey
> Add Segment key to bascfg

- root-applications/ibm-mas-account-root/templates/000-cluster-appset.yaml
- root-applications/ibm-mas-cluster-root/templates/000-ibm-operator-catalog-app.yaml
- root-applications/ibm-mas-cluster-root/templates/010-ibm-redhat-cert-manager-app.yaml
- root-applications/ibm-mas-cluster-root/templates/020-ibm-dro-app.yaml
- root-applications/ibm-mas-cluster-root/templates/040-cis-compliance-app.yaml
- root-applications/ibm-mas-cluster-root/templates/050-nvidia-gpu-operator-app.yaml
- root-applications/ibm-mas-cluster-root/templates/060-ibm-db2u-app.yaml
- root-applications/ibm-mas-cluster-root/templates/099-instance-appset.yaml
- root-applications/ibm-mas-instance-root/templates/100-ibm-sls-app.yaml
- root-applications/ibm-mas-instance-root/templates/120-db2-databases-appset.yaml
- root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
- root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml
- root-applications/ibm-mas-instance-root/templates/220-ibm-mas-workspace.yaml
- root-applications/ibm-mas-instance-root/templates/500-masapp-appset.yaml
https://jsw.ibm.com/browse/MASCORE-2318
> Fix issues with slack_channel_id annotation

- .github/workflows/update-internal-repo.yaml
- README.md
Fixes condition check if the remote target repo pull fails as the branch isn't there.
> fix github action coniidtion check

- root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml
Issue - https://jsw.ibm.com/browse/MASCORE-2416?filter=-1
Changes in this PR - 
changes to template of mas_app_server_bundles_combined_add_server_config.yaml
> [minor] [mascore-2416] Allow Manage bundle additonalServerConfig setting

- instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
Add SA for delete, get, scale, watch, and update operations in cpd functions
> add SA for cluster operations in cpd

- instance-applications/080-ibm-cp4d/templates/02-ibm-cp4d_rbac.yaml
- instance-applications/080-ibm-cp4d/templates/04-ibm-cp4d_prereqs_ops.yaml
- instance-applications/090-ibm-wsl/templates/01-ibm-wsl_ServiceAccount.yaml
- instance-applications/090-ibm-wsl/templates/04-ibm-wsl-post-verify.yaml
Fix instance_id typo and check before patching runtimes service accounts
> [patch] add bug fixes for cp4d and wsl

- instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_dns_Job.yaml
This PR has logic changes to remove guard while invoking the dns role as new job will get invoked if .Values changes
> [patch] Remove guard while invoking the dns role

- instance-applications/130-ibm-mas-suite/templates/04-ibm-mas_Suite.yaml
- root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
Issue - https://jsw.ibm.com/browse/MASCORE-3060
This PR has logic to add podTemplate to Suite CR
> [minor] [mascore-3060] adding podTemplate to Suite CR

- instance-applications/120-ibm-db2u-database/templates/03-db2ucluster.yaml
Adds nodeAffinity and tolerations to db2u as per https://www.ibm.com/docs/en/db2/11.5?topic=dducr-deploying-db2-using-db2uinstance-custom-resource#db2_cluster_api_11-5-8__deploy_on_dednode__title__1
> Adds extra db2u nodeAffinity and tolerations 

- instance-applications/010-ibm-sync-jobs/templates/00-aws-docdb-add-user_Job.yaml
- instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
- instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_certs_Job.yaml
- instance-applications/010-ibm-sync-jobs/templates/PostDelete-aws-docdb-remove-user_Job.yaml
- instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
Use the mikefarah implementation of yq to standardise on the one used in the cli
> Use expected yq implementation

- instance-applications/510-550-ibm-mas-suite-app-config/templates/01-ibm-manage_attachments_secrets.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/01-ibm-manage_logging_secrets.yaml
- root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml
Adds the secrets needed for Manage when atttachments or logging is configured.
> Add manage attachement and logging secrets

- .github/workflows/docs.yml
- build/bin/build-docs.sh
- mkdocs.yml
https://jsw.ibm.com/browse/MASCORE-3140
Worked on dev  branch.
Workflow: https://github.com/ibm-mas/gitops/actions/runs/10509705309
Published docs: https://ibm-mas.github.io/gitops/dev/
> Automated versioned documentation publication (#182)

- instance-applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml
https://jsw.ibm.com/browse/MASCORE-3750
> [patch] Do not re-enable TLS in DB2DB postsync job

- docs/timings.md
- mkdocs.yml
Adds the approx deployment timings for each app.
> [patch] Add deployment timings page

- sub-charts/junitreporter/templates/00-presync-report-starter.yaml
- sub-charts/junitreporter/templates/10-postsync-report-starter.yaml
For the junitreporter pick up the master changes rather than latest from cli
> [patch] Pick up master cli changes

- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-verify.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-sanity.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-verify.yaml
- sub-charts/junitreporter/templates/00-presync-report-starter.yaml
- sub-charts/junitreporter/templates/10-postsync-report-starter.yaml
sanity.py::test_usage_reporter
sanity.py::test_bgtasks_api
sanity.py::test_dltasks_api
sanity.py::test_trained_models_api
sanity.py::test_webapis_api
sanity.py::test_apikeys_api
sanity.py::test_dlm_api
sanity.py::test_datasets_api
sanity.py::test_create_demo_dataset_api
sanity.py::test_delete_demo_dataset_api
sanity.py::test_uploads_api
sanity.py::test_profiles_api
sanity.py::test_system_configs_api
sanity.py::test_projects_api
sanity.py::test_create_demo_project_api
sanity.py::test_delete_demo_project_api
- update verify suite verify.py::test_expected_reconciled_version
> [minor] Add Sanity tests for MVI

- instance-applications/120-ibm-aiopenscale/templates/01-ibm-aiopenscale-cr.yaml
According to CP4D team the aiopenscale cr name should be aiopenscale
> [patch] Change ibm-aiopenscale-cr name to aiopenscale

- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-maximoit-sanity.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-maximoit-verify.yaml
Take changes from https://github.com/ibm-mas/gitops/pull/233 and https://github.com/ibm-mas/gitops/pull/242 and incorporate into gitops
Added Sanity (invasive) Testcases for Maximo IT.
To verify Maximo IT version detail in system info
Test to verify Self Serve is installed
Test to verify Service View is installed
To test create a incident and validate its creation
To test create a Asset and validate its creation
To test create a ticket template and validate its creation
To test create a Solution and validate its creation
To test create a problem and validate its creation
To test create a change request and validate its creation
To test create a Service Request and validate its creation
To test create a Bulletin Message and validate its creation
Test to get all incidents
Test fetching all …
> [minor] Add sanity and verify tests for Maximo IT

- cluster-applications/060-custom-sa/templates/03-postsync-update-sm_rbac.yaml
- cluster-applications/060-custom-sa/templates/04-postsync-update-sm_Job.yaml
- root-applications/ibm-mas-cluster-root/templates/060-custom-sa.yaml
https://jsw.ibm.com/browse/MASCORE-4479
Store the generated custom service account secrets in AWS Secrets Manager.
> [patch] Store custom service account secrets in AWS Secrets Manager

- docs/drawio/appstructure.drawio
MASCORE-5561
Update the app diagram to include the Instana Agent Operator.
> [patch] update apps diagram for Instana

- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-maximoit-verify.yaml
Fixes the label used in the test record for the maximoit verification tests
> [patch] Fix maximoIT test record label

- instance-applications/111-ibm-minio/Chart.yaml
- instance-applications/111-ibm-minio/README.md
- instance-applications/111-ibm-minio/templates/02-minio-pvc.yaml
- instance-applications/111-ibm-minio/templates/03-minio-deployment.yaml
- instance-applications/111-ibm-minio/templates/04-minio-service.yaml
- instance-applications/111-ibm-minio/templates/05-minio-route.yaml
- instance-applications/111-ibm-minio/values.yaml
- root-applications/ibm-aibroker-instance-root/templates/020-ibm-minio-app.yaml
- root-applications/ibm-aibroker-instance-root/values.yaml
added helm charts for the minio and added minio argo cd app file , modified values.yaml file
> change related to minio storage

- instance-applications/111-ibm-minio/templates/02-minio-pvc.yaml
- instance-applications/111-ibm-minio/templates/03-minio-deployment.yaml
- instance-applications/111-ibm-minio/templates/04-minio-service.yaml
- instance-applications/111-ibm-minio/templates/05-minio-route.yaml
- instance-applications/111-ibm-minio/values.yaml
- root-applications/ibm-aibroker-instance-root/templates/020-ibm-minio-app.yaml
- root-applications/ibm-aibroker-instance-root/values.yaml
values that are used in minio helm are updated
> values updated for minio

- instance-applications/550-ibm-mas-addons-config/Chart.yaml
- instance-applications/550-ibm-mas-addons-config/templates/01-allowlist-cr.yaml
- root-applications/ibm-mas-instance-root/templates/550-ibm-mas-addons-config.yaml
Issue: [MASCORE-6280](https://jsw.ibm.com/browse/MASCORE-6280)
1. Creation of allowlist CR of genericaddon using a separate argo application addons-<clusterid>-<instanceid>
2. Going forward, all the generic addon CRs of different addon type can be created here
Tested in noble7 argo
> [minor] Update Allow Listing to catalog and Generic AddOn

- instance-applications/550-ibm-mas-addons-config/templates/02-additional-vpn-cr.yaml
- root-applications/ibm-mas-instance-root/templates/550-ibm-mas-addons-config.yaml
Kindly review and approve PR for below JIRA:
https://jsw.ibm.com/browse/MASR-2104
https://jsw.ibm.com/browse/MASR-3363
Screenshot for CR creation on openshift console:
> [minor] Catalog Additional VPN

- instance-applications/550-ibm-mas-addons-config/templates/01-allowlist-cr.yaml
- instance-applications/550-ibm-mas-addons-config/templates/02-additional-vpn-cr.yaml
- instance-applications/550-ibm-mas-addons-config/templates/02-enhanced-dr-cr.yaml
- instance-applications/550-ibm-mas-addons-config/templates/04-extensions-cr.yaml
- root-applications/ibm-mas-instance-root/templates/550-ibm-mas-addons-config.yaml
Issue: [MASCORE-6453](https://jsw.ibm.com/browse/MASCORE-6453)
- Creation of Generic addon CR for extensions addon if extensions is enabled
- Also removed ibm-mas prefix from CR to support changes done in https://github.ibm.com/maximoappsuite/coreapi/pull/2539
Tested in noble4 argocd
> [minor] Catalog Java Extensions add-on using generic add-on mechanism

- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-sanity.yaml
- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-verify.yaml
> [patch] Update MVI Saas test to use super-user secret for 9.1.x

- instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
MASCORE-8251 : wo crud operation added for 9.1 and above
> [patch] MASCORE-8251 : wo crud operation added for 9.1 and above

- instance-applications/115-ibm-aibroker-tenant/templates/08-aibroker-postsyncjob.yaml
Gitops fix postsync job aiservice manage integration support multi-tenant
Job Role, RB, SA name update because same resource access problem.
> [Minor] Gitops fix postsync job AIService with manage integration

- instance-applications/120-ibm-db2u-database/files/PostBackFlow.sh
Removing the below line as it is failing for associated files are not generating while running post backflow script  
cat ${INSTHOME}/Managed/OwnerCheck.txt
> [patch] Update PostBackFlow.sh
