ibm-mas/gitops

README.md
applications/010-redhat-cert-manager/templates/00-cert-manager_Namespace.yaml
applications/020-ibm-dro/templates/00-dro_Namespace.yaml
applications/020-ibm-dro/templates/08-postsync-update-sm_Job.yaml
applications/040-cis-compliance/templates/01-cis-compliance_Namespace.yaml
applications/050-nvidia-gpu-operator/templates/00-nfd_Namespace.yaml
applications/050-nvidia-gpu-operator/templates/04-gpu_Namespace.yaml
applications/060-ibm-db2u/templates/00-db2_Namespace.yaml
applications/060-ibm-db2u/templates/00-db2_NamespaceScope.yaml
applications/100-ibm-sls/templates/01-ibm-sls_namespace.yaml
applications/130-ibm-db2u-jdbc-config-rotate-password/templates/00-db2u_jdbccfg-credentials.yaml
applications/130-ibm-db2u-jdbc-config/templates/01-suite_jdbccfg.yaml
applications/130-ibm-mas-suite/templates/00-ibm-mas_namespace.yaml
applications/500-ibm-mas-suite-app-install/templates/01-ibm-mas_namespace.yaml
root-applications/ibm-mas-account-root/templates/000-cluster-appset.yaml
root-applications/ibm-mas-cluster-root/templates/000-ibm-operator-catalog-app.yaml
root-applications/ibm-mas-cluster-root/templates/010-ibm-redhat-cert-manager-app.yaml
root-applications/ibm-mas-cluster-root/templates/020-ibm-dro-app.yaml
root-applications/ibm-mas-cluster-root/templates/040-cis-compliance-app.yaml
root-applications/ibm-mas-cluster-root/templates/050-nvidia-gpu-operator-app.yaml
root-applications/ibm-mas-cluster-root/templates/060-ibm-db2u-app.yaml
root-applications/ibm-mas-cluster-root/templates/099-instance-appset.yaml
root-applications/ibm-mas-instance-root/templates/100-ibm-sls-app.yaml
root-applications/ibm-mas-instance-root/templates/120-db2-databases-appset.yaml
root-applications/ibm-mas-instance-root/templates/130-configs-appset.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
root-applications/ibm-mas-instance-root/templates/220-ibm-mas-workspace.yaml
root-applications/ibm-mas-instance-root/templates/500-masapp-appset.yaml

At present our root applications always targets the openshift-gitops namespace, e.g. https://github.com/ibm-mas/gitops/blob/fa480bc16bc03f2d1654d24a947cbc9c2f0efc29/root-applications/ibm-mas-account-root/templates/000-cluster-appset.yaml#L8
However, this is not always the namespace we need to use. E.g. in MCSP we need "argocd-worker".
This PR looks for `argoapp_namespace parameter` on the root application. Its value is passed down and used by all child applications.
Accompanying PR: https://github.com/ibm-mas/cli/pull/836
Tested by spinning up a MAS instance (with MVI) in noble3 (Fyre) using an ArgoCD instance that expects Applications and ApplicationSets to be creatred in a different namespace (`argocd` instead of `openshift-gitops`). Verified that everything still works and that all …

Allow target namespace for root applications to be configured

---

applications/130-ibm-db2u-jdbc-config/templates/00-presync-create-db2-user_Job.yaml

[MASCORE-2096](https://jsw.ibm.com/browse/MASCORE-2096)
Verified by creating the Job resource manually in the fvtsaas cluster. Output logs:
```
================================================================================
Settings
================================================================================
DB2_NAMESPACE ....................... db2u
DB2_INSTANCE_NAME ................... db2wh-rick-manage
DB2_DBNAME .......................... BLUDB
DB2_CREDENTIALS_SECRET_PATH ......... /etc/mas/creds/db2-credentials
================================================================================
Checking DB2 CRD db2uclusters.db2u.databases.ibm.com is ready (retries every ~10 seconds for ~5 minutes)
================================================================================ …
```

Execute "user exists check" command on correct db2u pod

---

applications/100-ibm-sls/templates/07-postsync-update-sm_Job.yaml

This PR causes the ibm-sls Application to run the code that updates the sls secret in AWS SM as a normal job, instead of as a PostSync hook.
Since normal jobs are taken into account when computing the health status of an ArgoCD application, this change ensures that the secret is established before ArgoCD proceeds to sync applications in later syncwaves that depend on this secret (e.g. ibm-mas-sls-config).
The job is in the last syncwave within this application so should only be started once the SLSCfg CR reports Ready=True. As a further precaution, I've mounted the required ConfigMap into the Job pod (rather than looking it up via the K8S API), which will cause K8S to wait for the configmap to appear before attempting to start the Job.
I've verified that the Job works as expected, and …

Ensure sls secret is updated before proceeding to subsequent syncwaves

---

applications/130-ibm-db2u-jdbc-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-kafka-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-mas-bas-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-mas-idp-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-mas-sls-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-mas-smtp-config/templates/postdelete-delete-cr.yaml
applications/130-ibm-mas-suite/templates/01-postdelete-crs-resources.yaml
applications/130-ibm-objectstorage-config/templates/postdelete-delete-cr.yaml
root-applications/ibm-mas-instance-root/templates/120-db2-databases-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml

The Config CR PostDeletion hooks added under https://github.com/ibm-mas/gitops/pull/42 weren't actually working as I thought -  ArgoCD's resource finalizer was not being set on the config apps meaning that things were not being cleaned up properly in some cases. After enabling the finalizer, config app deletion would hang due to the resources (rbac, networkpolicy) that the hook job depends on being deleted before the Job gets a chance to run. 
This PR provides a workaround for this; the supporting rbac, networkpolicy resources are created in the ibm-mas-suite chart, meaning they will persist beyond the lifetime of individual config applications. This approach also reduces code and resource duplication.
NOTE: This works fine when deleting/recreating configs (without removing the suite). …

Fixes to Config CR PostDelete hooks

---

applications/010-redhat-cert-manager/templates/04-postsync-update-sm_Job.yaml
applications/020-ibm-dro/templates/08-postsync-update-sm_Job.yaml
applications/100-ibm-sls/templates/07-postsync-update-sm_Job.yaml
applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml

https://jsw.ibm.com/browse/MASCORE-2279
This PR changes all existing PostSync hooks responsible for updating AWS SM with secrets needed in subsequent sync waves to just be "ordinary" kubernetes Jobs (i.e. the `argocd.argoproj.io/hook: PostSync` annotation has been removed from the Jobs and supporting resources).
This has the effect of making the Jobs part of the main sync cycle for an application, thus ensuring that ArgoCD will wait for the Jobs to complete successfully before allowing resources in subsequent syncwaves that depend on these secrets to proceed.
The change has two main side effects that have required some further modifications:
-  the job runs themselves are no longer deferred until after the application they belongs to is fully synced and healthy. To address this I've added …

Guard against race conditions in post-sync hooks

---

applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml
applications/90-ibm-sync-resources/templates/01-aws-docdb_Secret.yaml
applications/91-ibm-sync-jobs/templates/00-aws-docdb-add-user_Job.yaml
applications/91-ibm-sync-jobs/templates/00-placeholder_ConfigMap.yaml
applications/91-ibm-sync-jobs/templates/PostDelete-aws-docdb-remove-user_Job.yaml
root-applications/ibm-mas-instance-root/templates/120-db2-databases-app.yaml
root-applications/ibm-mas-instance-root/templates/90-ibm-sync-resources.yaml
root-applications/ibm-mas-instance-root/templates/91-ibm-sync-jobs.yaml

The PR combines fixes for two bugs:
- [db2u apply settings not consistent](https://jsw.ibm.com/browse/MASCORE-2427)
- [ibm-sync-resources application fails to deploy when docdb_port is numeric](https://jsw.ibm.com/browse/MASCORE-2563)
We need some custom configuration to be applied to the DB2 Database setup for Manage (otherwise Manage FVTs will fail down the line).
We set these parameters on the DbuCluster CR, but this is not sufficient as the DB2 operator does not (at present) automatically apply them. Instead, as documented [here](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=administering-changing-db2-warehouse-configuration-settings), a script /db2u/scripts/apply-db2cfg-settings.sh must be executed on one of the db2u pods. However, this does not always seem to work and …

Fix "db2u apply settings not consistent" and "ibm-sync-resources application fails to deploy when docdb_port is numeric"

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/01-ibm-manage_customization_archive_secrets.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml

Issue: https://jsw.ibm.com/browse/MASCORE-2417?filter=-1
What changed in this PR:
Added support to read secretName from manage mas_appws_spec, and created K8S secret.
mas_appws_spec will only have the secret name.
The actual secret with the username and password will be pre-created by SRE team following the below naming convention. 
`arn:aws:secretsmanager:<<region>>:<<aws_account>>:secret:<<account>>/<<cluster>>/<<mas_instance>/<<secret_name>>
`
The ManageWorkspace CR can have a customizationList section like this:
```
customizationList:
- customizationArchiveCredentials:
secretName: masdev-manage-cl0--cac--sn
customizationArchiveName: fvtcustomarchive
customizationArchiveUrl: >-
https://na.artifactory.swg-devops.com/artifactory/wiotp-generic-release/maximoappsuite/fvt-ibm-mas-manage/late …
```

 [minor] [mascore-2417] Add support for Manage customizationList 

---

instance-applications/130-ibm-db2u-jdbc-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-kafka-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-bas-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-idp-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-mongo-config/templates/01-mongo-credentials_Secret.yaml
instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-sls-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-smtp-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-objectstorage-config/templates/postdelete-delete-cr.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml

This issue was being caused by the fact that the suite and the suite-config apps are all in syncwave 130. This is necessary since the suite app depends on system mongo/bas/sls suite-config apps to become healthy when standing up a new MAS instance. 
However, on teardown, this meant that the suite app is pruned at the same time as the suite-config apps, meaning the suite-config entity managers were being torn down before processing completed on the suite-config CR finalizers and causing deletion of the CR to hang indefinitely.
This PR solves this issue by annotation the suite app with `argocd.argoproj.io/sync-options: PruneLast=true`. This causes ArgoCD to issue deletion of the suite app (and thus the suite CR) only once the suite-config app deletions have completed.
Note: this will likely …

Fix MAS Config CRs deletion hangs if Suite is deleted at the same time

---

root-applications/ibm-mas-account-root/templates/000-cluster-appset.yaml
root-applications/ibm-mas-cluster-root/templates/000-ibm-operator-catalog-app.yaml
root-applications/ibm-mas-cluster-root/templates/010-ibm-redhat-cert-manager-app.yaml
root-applications/ibm-mas-cluster-root/templates/020-ibm-dro-app.yaml
root-applications/ibm-mas-cluster-root/templates/040-cis-compliance-app.yaml
root-applications/ibm-mas-cluster-root/templates/041-cis-compliance-cleanup.yaml
root-applications/ibm-mas-cluster-root/templates/050-nvidia-gpu-operator-app.yaml
root-applications/ibm-mas-cluster-root/templates/060-ibm-db2u-app.yaml
root-applications/ibm-mas-cluster-root/templates/099-instance-appset.yaml
root-applications/ibm-mas-instance-root/templates/000-ibm-sync-resources.yaml
root-applications/ibm-mas-instance-root/templates/010-ibm-sync-jobs.yaml
root-applications/ibm-mas-instance-root/templates/100-ibm-sls-app.yaml
root-applications/ibm-mas-instance-root/templates/120-db2-databases-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml
root-applications/ibm-mas-instance-root/templates/200-ibm-mas-workspaces.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-assist-install.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-iot-install.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-manage-install.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-visualinspection-install.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-health-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-monitor-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-optimizer-install.yaml
root-applications/ibm-mas-instance-root/templates/540-ibm-mas-masapp-predict-install.yaml

The default tracking method used in argocd means that a label gets added to each resource Argo creates. The kubernetes label values lengths need to be 63 characters or less. As we generate our ArgoCD Application names then it is quite easy to breach this limit. This PR will shorten the name but still keep the uniqueness of the app names.
The main change is to remove the `account_id.region_id` section in the argocd app names. This assumes that the OCP cluster name is uniquely named across the different accounts and regions that might be installed via the same ArgoCD instance. All these apps also have labels added to list the account, region, cluster, instance where applicable.
One difference is the mas_config_name value which already contains the mas instance id so the mas_instance_id is …

Use shorter name for ArgoCD app names

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/01-ibm-manage_customization_archive_secrets.yaml

Issue - https://jsw.ibm.com/browse/MASCORE-2802
Update k8s secret which gets created due to customizationList section to below format
stringData:
credentials: |
user={{ $value.username }}
password={{ $value.password }}

[patch] [mascore-2802] - update secret template

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-verify.yaml

Adds a post sync job that runs some verification tests on Manage. These are fairly simple without haveing to create an apikey. These will
- check reconciled version is the exepcted value
- checks the status shows the same as the spec for languages
- checks the status shows the same as the spec for serverBundles
- checks the expected addon/components are installed and enabled
Tested in an environment with Manage, and the job completes
https://jsw.ibm.com/browse/MASCORE-1186

Add Manage verification

---

instance-applications/000-ibm-sync-resources/templates/01-aws_Secret.yaml
instance-applications/130-ibm-mas-mongo-config/templates/01-mongo-credentials_Secret.yaml
instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml

Issue - https://jsw.ibm.com/browse/MASCORE-2636?filter=-1
When a MAS instance is removed, we should also remove the MAS entries in the mongodb
This removal is controlled via a param `wipe_mongo_data`.

[minor] [mascore-2636] Delete mongodb entries when removing MAS instance

---

instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_certs_Job.yaml
instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_dns_Job.yaml

Changes to the PR:-
- Update to job name - so job can be recreated if values change 
- remove ttlSecondsAfterFinished (as this removes the job and gitops recreates it again )

[patch] update job name - so job can be recreated if values change

---

root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml

Adds correct label to mas-xxx-core namespace to ensure ArgoCD will track it (and thus delete it) when the suite app is pruned.
[MASCORE-2818](https://jsw.ibm.com/browse/MASCORE-2818)
With this change, the mas-xxx-core namespace (created implicitly due to `syncOptions.CreateNamespace=true` being set on the suite app) is tracked properly by ArgoCD. We can see it appears as a child resource of the suite app:
Verified that when the suite config file is deleted from the config repo (e.g. gitops-envs) causing the suite app to be pruned,  ArgoCD now deletes the mas-xxx-core namespace as expected.

Ensure mas-xxx-core namespace is cleaned up when MAS is torn down

---

instance-applications/500-540-ibm-mas-suite-app-install/templates/04-ibm-mas-mvi_ResourceQuota.yaml
instance-applications/500-540-ibm-mas-suite-app-install/values.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-visualinspection-install.yaml

Adds a ResourceQuota if the app is visualinspection, to control the `requests.nvidia.com/gpu` for that namespace

[minor] Add MVI Resource Quota

---

instance-applications/010-ibm-sync-jobs/templates/00-aws-docdb-add-user_Job.yaml

This PR has logic change to construct comma separated docdb:host to support connection via mongosh
Re: https://github.com/ibm-mas/ansible-devops/pull/1374

[patch] support for multiple docdb host and port

---

instance-applications/000-ibm-sync-resources/templates/01-02-aws-db2-user-job_ServiceAccount.yaml
instance-applications/130-ibm-jdbc-config/templates/postdelete-delete-db2-user_Job.yaml

During the App provisioning pipeline we create JdbcCfg bindings for the DB2 databases provisioned for IoT (system) and Manage (wsapp). As part of these tasks, we generate a username/password and create them as new LDAP user in the DB2 database instance. 
When these bindings are removed by the pipeline as a result of deprovisioning the MAS instance (or removing IoT/Manage), we should revoke these credentials.
Note: Since the DB2 databases are dedicated for the MAS instance, this step is not critical and should be tolerant of failure.

[patch][mascore1597] Revoke LDAP user credentials during deprovisioning

---

.github/workflows/docs.yml
build/bin/build-docs.sh
mkdocs.yml

https://jsw.ibm.com/browse/MASCORE-3140

Automated versioned documentation publication

---

instance-applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml

https://jsw.ibm.com/browse/MASCORE-3750

[patch] Do not re-enable TLS in DB2DB postsync job 

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/01-ibm-manage_encryption_secret.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml

Adds new manage encryption secret. This contains the key/values defined under the new `manage.global_secrets_yaml` property. See [saas-envs PR](https://github.ibm.com/maximoappsuite/saas-envs/pull/183/files).
Removes deprecated `manage_attachments_secret`
https://jsw.ibm.com/browse/MASCORE-3747
Tested in `noble5`:

[patch] Redo Manage Attachment configuration support in SaaS/gitops 

---

instance-applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/01-ibm-manage_encryption_secret.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml

Adds new manage encryption secret. This contains the key/values defined under the new `manage.global_secrets_yaml` property. See [saas-envs PR](https://github.ibm.com/maximoappsuite/saas-envs/pull/183/files).
Removes deprecated `manage_attachments_secret`
https://jsw.ibm.com/browse/MASCORE-3747
Tested in `noble5` and `fvtsaas`:

[patch] Redo Manage Attachment configuration support in SaaS/gitops

---

instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_certs_Job.yaml
instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_dns_Job.yaml
root-applications/ibm-mas-account-root/templates/000-cluster-appset.yaml
root-applications/ibm-mas-cluster-root/templates/099-instance-appset.yaml

Adds the `retry.limit` for the ArgoCD instance and cluster appsets, and sets it to unlimited (-1). This means that argocd will continue to sync until it is ready and won't fail when the default (5) failures are reached. This is needed as we see many temporal failures in each app that is just a failure until another app is ready. 
This change also changes the syncwave of the suite certs and dns jobs so it runs at the same time as the olm job, as these jobs can take 15 minutes, and was blocking the olm job from running when it could have run at the same time.
Tested in fvtsaas and it all works

[patch] Add unlimited retries and fix suite cert/dns sync

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-verify.yaml

Ensures default system CA certs are included in the trust chain used when making HTTP calls to MVI endpoints via python `requests`. This allows the MVI tests to work properly when MAS is configured to use an external frontend such as CIS as certificates presented by these frontends will always be signed by a well-known CA trusted by default system CA certs.
We also include the additional `certificate` field from the MVI route as this may include a necessary intermediate CA cert in some cases.
https://jsw.ibm.com/browse/MASCORE-3790
Verified approach in MAS envs by checking that including the additional certificates will mean HTTP calls made via python `requests` will now trust certificates presented by the endpoints in the following envs:
- `fvtsaas`  (`dns_provider: cis`, `manual_certs: …

[patch] MVI verification tests uses default certs, certificate and caCertificate in HTTP calls to MVI

---

instance-applications/120-ibm-db2u-database/templates/00-presync-await-crd_Job.yaml
instance-applications/130-ibm-jdbc-config/templates/00-presync-create-db2-user_Job.yaml
instance-applications/130-ibm-jdbc-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-jdbc-config/templates/postdelete-delete-db2-user_Job.yaml
instance-applications/130-ibm-kafka-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-bas-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-idp-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-mongo-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-sls-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-mas-smtp-config/templates/postdelete-delete-cr.yaml
instance-applications/130-ibm-objectstorage-config/templates/postdelete-delete-cr.yaml
instance-applications/500-540-ibm-mas-suite-app-install/templates/00-presync-add-mvi-scc_Job.yaml
instance-applications/500-540-ibm-mas-suite-app-install/templates/06-postsync-add-mvi-scc_Job.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-verify.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-verify.yaml

When a hook completed we was leaving a number of resource around as these were not removed until the hook ran again. The delete policy was changed to hook succeeded.
In the case where the hook failed we still want to remove it as it would block further calls when the resource is a job as the max number of pods for the job would be reached. In this case we want to add the BeforeHookCreation policy so that is it removed before the hook is creation, but we want to keep the resources (pods of the jobs) around for debugging.

[patch] Change hook delete policy to both HookSucceeded and BeforeHookCreation

---

root-applications/ibm-mas-instance-root/templates/120-db2-databases-app.yaml

Don't use dot notation for reportername as it gets added to mongo incorrectly.

[patch] Fix reporter_name for db2

---

sub-charts/junitreporter/templates/00-presync-report-starter.yaml
sub-charts/junitreporter/templates/10-postsync-report-starter.yaml

When a sync is compelted once and marked in the devopsdb, we don't want another sync later on changing the times. This change keeps the configmap around and the post sync job just updates it with the sync_complete time. Any further syncs after this point will not update the devopsdb.

[patch] Only register the start on the first sync in devopsdb

---

sub-charts/junitreporter/templates/00-presync-report-starter.yaml
sub-charts/junitreporter/templates/10-postsync-report-starter.yaml

The junitreporter was creating network policies with the same name in each chart, this caused some warnings in Argo. Changed the name of the networkpolicy to be unique

[patch] Create unique networkpolicies for junitreporter

---

root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-visualinspection-install.yaml
sub-charts/junitreporter/templates/00-presync-report-starter.yaml
sub-charts/junitreporter/templates/10-postsync-report-starter.yaml

The prefix name was too long when used with apps like visualinspection.

[patch] Decrease prefix name of juniutreporter

---

instance-applications/110-ibm-cp4d-operators/templates/02-ibm-cp4d_rbac.yaml
instance-applications/110-ibm-cp4d/templates/07-ibm-cp4d_patch_zenservice.yaml

The problem reported in technote https://www.ibm.com/support/pages/node/7158524 is impacting the cp4d install. This change implements the workaround noted by updating the patch zenservice job to execute the workaround. Tested in fvtsaas env:

[patch] Fix cp4d postgres license issue 

---

root-applications/ibm-mas-cluster-root/templates/099-instance-appset.yaml

The size of the instance application set can get to big for Argo to store all the data into etcd, when we have more than 1 revision history. The error you see in argo is:
```
failed to record sync to history: etcdserver: request is too large. 
```
Reducing the revision history to 1 so we have the current values and the previous values saved, solves the issue.

[patch] Set revision history to 1 on instance appset

---

instance-applications/220-ibm-mas-workspace/templates/05-postsync-add-label_Job.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-add-label_Job.yaml
root-applications/ibm-mas-instance-root/templates/200-ibm-mas-workspaces.yaml

The postsync jobs to add the labels had two issues:
1) they were not postsyncs
2) the suite job didn't pick up the workspace route as this is created later on. The workspace app needs its own add label job.
Tested in an env and the labels are set in the workspace app:

[patch] Fix add_labels postsync for routes

---

cluster-applications/010-redhat-cert-manager/templates/04-postsync-update-sm_Job.yaml
cluster-applications/020-ibm-dro/templates/08-postsync-update-sm_Job.yaml
cluster-applications/200-cluster-promotion/templates/02-cluster-verify_Job.yaml
cluster-applications/200-cluster-promotion/templates/03-cluster-promoter_Job.yaml
instance-applications/010-ibm-sync-jobs/templates/01-ibm-cp4d-presync.yaml
instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_certs_Job.yaml
instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_dns_Job.yaml
instance-applications/100-ibm-sls/templates/07-postsync-update-sm_Job.yaml
instance-applications/110-ibm-cp4d-operators/templates/04-ibm-cp4d_prereqs_ops.yaml
instance-applications/110-ibm-cp4d-operators/templates/04-ibm-cp4d_upg_cleanup.yaml
instance-applications/110-ibm-cp4d/templates/03-ibm-cp4d-mcs_patch_sa.yaml
instance-applications/110-ibm-cp4d/templates/07-ibm-cp4d_patch_zenservice.yaml
instance-applications/110-ibm-cp4d/templates/08-ibm-cp4d-post-verify.yaml
instance-applications/110-ibm-cp4d/templates/09-ibm-cp4d_services_base.yaml
instance-applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml
instance-applications/120-ibm-spss/templates/02-ibm-spss-post-verify.yaml
instance-applications/120-ibm-wsl/templates/02-ibm-wsl-post-verify.yaml
instance-applications/130-ibm-mas-suite/templates/05-postsync-add-label_Job.yaml
instance-applications/220-ibm-mas-workspace/templates/05-postsync-add-label_Job.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-add-label_Job.yaml

We use the adler32sum from the .Values to determine if a job should be re-run (as it will be a different name for the job). The problem was that the junitreporter.devops_build_number was included in these values and this changes with each build so the jobs were re-running when it wasn't needed.
The change omits the junitreporter key from the .values and uses the rest of the values which won't change unless there is an actual meaningful change.
Tested this out in fyre cluster, and it works.

[patch] Omit junitreporter from .Values when used in jobs

---

instance-applications/110-ibm-cp4d-operators/templates/01-ibm-cp4d_CatalogSources.yaml

In the update to cp4d 5.0, we added a catalog to install zen service 6.0.1 but what we needed was 6.0.2 and since we have that in ibm-catalog, we don't need to add the zen catalog which has the wrong version. This is a correction for that.

[patch] Remove unneeded zen catalog for cp4d 5.0

---

cluster-applications/200-cluster-promotion/templates/02-cluster-verify_Job.yaml
cluster-applications/200-cluster-promotion/templates/03-cluster-promoter_Job.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-verify.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-sanity.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-verify.yaml

Outputs the log and junitxml log to the test record configmap, so we can see what tests are run and what the output was.
Tested in fvt environment, and the configmap(s) now contains the following:

[minor] Output verify and sanity test log to test record

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-sanity.yaml

If the MVI CR is only just created then the usage job won't be present. Only run this test when it is more than one hour after the CR creation.

[patch] Only check mvi usage when over one hour

---

instance-applications/110-ibm-cp4d-operators/templates/02-ibm-cp4d_rbac.yaml
instance-applications/110-ibm-cp4d/templates/07-ibm-cp4d_patch_zenservice.yaml

Correct order for patch work on zen meta store cluster license and add checks for meeting conditions for patch.

[patch] fix for zen metastore patch work

---

instance-applications/130-ibm-mas-bas-config/templates/03-ibm-mas_BasCfg.yaml
instance-applications/130-ibm-mas-sls-config/templates/05-ibm-mas_SlsCfg.yaml
instance-applications/130-ibm-mas-smtp-config/templates/02-ibm-mas_SmtpCfg.yaml

Takes https://github.com/ibm-mas/cli/pull/1346 and allows the configured pod templates for bascfg, smtpcfg and slscfg to be set on the corrresponding CRs.
Tested in dev env

[minor] Add config pod templates

---

root-applications/ibm-mas-cluster-root/templates/060-selenium-grid.yaml

Fixes issue seen in fvtsaas:
```
Error: template: ibm-mas-cluster-root/templates/060-selenium-grid.yaml:33:41: executing "ibm-mas-cluster-root/templates/060-selenium-grid.yaml" at <8>: wrong type for value; expected string; got map[string]interface {}
```

[patch] fix selenium-grid app template

---

instance-applications/110-ibm-cp4d/templates/07-ibm-cp4d_Ibmcpd.yaml

Zen patch job is running before Ibmcpd even though they are in the same sync wave and this is causing cp4d to fail or run longer than intended. Since the job depends on ibmcpd, we need to run ibmcpd before the job to solve the problem. 
This is a temporary fix until we find a better approach.

[patch] change ibmcpd sync wave

---

root-applications/ibm-mas-cluster-root/templates/060-selenium-grid.yaml

The seleniumgrid release should just be selenium-grid as this controls what the servicename/route is called

[patch] Set releasename for seleniumgrid

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml

The Manage sanity tests to to pick up the route CA, the internal CA and the well known CA in order for the tests to work in all environments. Also some tests didn't verify the connection.
Test in fvtsaas
```
============================= test session starts ==============================
platform linux -- Python 3.9.19, pytest-8.3.3, pluggy-1.5.0 -- /mascli/.venv/bin/python
cachedir: /tmp/__pycache__
rootdir: /tmp/tests
collecting ... collected 12 items
../tmp/tests/tests.py::test_getManageComponents PASSED                   [  8%]
../tmp/tests/tests.py::test_getClusterInfo PASSED                        [ 16%]
../tmp/tests/tests.py::test_create_super_user_token PASSED               [ 25%]
../tmp/tests/tests.py::test_v3_create_user PASSED                        [ 33%] …
```

[patch] Fix manage sanity tests when used in manual cert or self-signed environment

---

root-applications/ibm-mas-instance-root/templates/000-ibm-sync-resources.yaml
root-applications/ibm-mas-instance-root/templates/010-ibm-sync-jobs.yaml
root-applications/ibm-mas-instance-root/templates/100-ibm-sls-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cp4d-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cp4d-operator-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cs-control-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-db2u-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-aiopenscale-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-spark-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-spss-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-wml-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-wsl-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml
root-applications/ibm-mas-instance-root/templates/200-ibm-mas-workspaces.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-manage-install.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-assist-install.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-iot-install.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-visualinspection-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-health-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-monitor-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-optimizer-install.yaml
root-applications/ibm-mas-instance-root/templates/540-ibm-mas-masapp-predict-install.yaml

When deploying multiple instances on the same cluster a warning was occurring as argo was trying to control the same reporter resources. These only appear when an app is syncing so you need the same apps for different instances synching at the same time.
Appended the instance id to the reporter name which is used as the prefix for the resources. Shorted the start of the app-install and app-config by 15 chars so we can fit it in.
Tested in mulit instance env

[patch] Add instance id to instance level reporters

---

instance-applications/120-ibm-db2u-database/templates/03-db2uinstance.yaml

Add a guard around db2 archivelogs if the storage class is not set as it is optional

[patch] Add guard around no archivelogs

---

instance-applications/120-ibm-db2u-database/templates/05-postsync-setup-db2_Job.yaml

When a value changes in the db2-db chart then we create a new postsync-setiup job. If that value is not related to a db config i.e. the db2 tls_version or even just a new version, then we always call the db2-apply script even if there is nothing to change. The db2apply script always restarts db2.
The check is to run the validate-config first and only if we detect some db2 config is not set then we should call apply (and then recheck)
Tested with the changes (the line `... db2 config already matches expected config, returning without calling apply-db2cfg-settings` is the new change):
```
Calling apply-db2cfg-settings.sh file on c-db2wh-inst1-manage-db2u-0
================================================================================
Loaded in-cluster configuration …
```

[patch] Only call db2apply when there is a change needed

---

instance-applications/130-ibm-mas-suite/templates/05-postsync-configtool-oidc.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml

These changes are part of the work to automate the registration of an OIDC client to support usage of the MAS Application Framework (MAF) configuration tool (https://jsw.ibm.com/browse/MASCORE-3763). 
This PR adds a new Job (and supporting resources) to the ibm-mas-suite Helm chart that picks up `oidc` configuration and uses it to register the oidc client if oidc config is present, or unregister the oidc client otherwise.
See https://github.com/ibm-mas/cli/pull/1437 for related changes and testing results.

[minor] gitops: automated configtool oidc registration

---

cluster-applications/053-falcon-operator/values.yaml

Fix the field name in the defaul Falcon Operator Helm values. Kubernetes resources such as `Deployment` use the standard name `terminationGracePeriodSeconds` for this field, but it's actually `terminationGracePeriod` in the `FalconNodeSensor` CRD.
Reference: https://github.com/CrowdStrike/falcon-operator/blob/main/docs/resources/node/README.md

[patch] Fix default Falcon Helm values field

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/700-702-postsync-db2-manage.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml

These changes disable various destructive/disruptive Manage Admin API routes in production instances. The routes are re-enabled if the instance transitions from production -> nonproduction (not sure this will ever happen, but just in case).
The existing `ibm_mas_suite.mas_annotation.mas.ibm.com/operationalMode` annotation is used to determine whether this is a production instance or not. 
~This is provisional, awaiting confirmation that this is the correct approach. I will leave this PR as draft until I get this confirmation.~ Confirmed with @benbakowski.
https://jsw.ibm.com/browse/MASCORE-4639
When mas-instance-params.yaml has:
```
mas_instance:
annotations:
mas.ibm.com/operationalMode: production
```
the `postsync-db2-manage` job appends the following to the SQL script that it executes …

[minor] Disable destructive/disruptive Manage admin API routes in production instances

---

cluster-applications/030-ibm-cis-cert-manager/templates/00-8-ibm-cis-webhook_cis-ingress-controller.yaml
instance-applications/130-ibm-mas-suite/templates/05-postsync-add-label_Job.yaml
instance-applications/130-ibm-mas-suite/templates/06-postsync-configtool-oidc.yaml
instance-applications/220-ibm-mas-workspace/templates/05-postsync-add-label_Job.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-add-label_Job.yaml

Two issues are resolved by this PR:
An issue was identified when running in `ingress: true` mode whereby the `configtool-oidc` job would fail with HTTP 526 "Invalid SSL certificate" when it attempted to call the external `/oidc/endpoint/MaximoAppSuite/registration` route.
This was because the `add-label` job responsible for adding the `type: external` label to MAS routes (necessary for them to function properly in `ingress: true` mode) was annotated as an ArgoCD `PostSync` hook, but the `configtool-oidc` is not. This meant that `configtool-oidc` would run *before* `add-label`, but would fail and never allow `add-label` to run.
This PR resolves this problem by removing the `PostSync` label from the `add-label` job and ensures it runs before `configtool-oidc` by allocating it to an earlier …

[patch] Ensure external label added to routes prior to configtool oidc registration attempt. Fix `.Values.ingress` checks.

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml

Fixes three issues with manage sanity tests:
1) if we go down the path where the asset is not found then we get a python error as the delete_asset doesn't have the manage_host_ca_filepath passed in.
2) When there are mulitple manage instances on the cluster then the cluster role and cluster rolebinding clash with other instances as these are not tidied to a namespace. SO appending the mas instance id to the name of these.
3) Removes the delete_asset call in the manage sanity test as this will only work when a dbc is applied that would allow the delete of an asset to be allowed. There is no issues with multiple assets being created.

[patch] Fix for sanity tests in manage

---

instance-applications/130-ibm-mas-suite/templates/06-postsync-configtool-oidc.yaml

https://jsw.ibm.com/browse/MASCORE-5635
Simple PR to change postsync-oidc job to access the oauth-admin-secret via a volume mount rather than env vars, as per IBM policy. 
This will resolve the operator-maturity test case failure seen in fvtsaas.
Changes verified in noble6:
and fvtsaas:

[patch] read oauth_admin_secret via volumeMount

---

instance-applications/120-ibm-db2u-database/templates/04-db2u-Backup_Cron.yaml
instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
instance-applications/120-ibm-db2u-database/templates/09-hadr_services.yaml
instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml
root-applications/ibm-mas-instance-root/templates/120-db2-databases-app.yaml

Issue: [MASCORE-5741](https://jsw.ibm.com/browse/MASCORE-5741)
1. Creates HADR service for both primary and standby if replica_db is enabled
2. Creates post sync hadr job that copies backup from primary to standby, restores the database and applies configuration on standby db2 pod. It then starts HADR on standby and primary
3. We also stop HADR in primary in case replica_db is disabled (Otherwise it will lead to database in inconsistent state)
Tested in noble4 ajw0111 instance
```
================================================================================
Waiting for pod c-db2wh-ajw0111-manage-sdb-db2u-0 to be present before continuing (timeout 300s)
================================================================================
... attempt 1 of 10
NAME …
```

[minor] Automate the HADR setup during provisioning

---

instance-applications/010-ibm-sync-jobs/templates/00-ibm-cp4d-olm-480.yaml
instance-applications/010-ibm-sync-jobs/templates/00-ibm-cp4d-olm-481.yaml
instance-applications/010-ibm-sync-jobs/templates/00-ibm-cp4d-olm-500.yaml
instance-applications/010-ibm-sync-jobs/templates/00-ibm-cp4d-olm-510.yaml
instance-applications/010-ibm-sync-jobs/templates/00-ibm-cp4d-presync.yaml
root-applications/ibm-mas-instance-root/templates/010-ibm-sync-jobs.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cp4d-app.yaml

Pipeline is breaking because the presync job that puts the values in secret manager has not run before cp4d so moving the job back to the sync-job app. 
Tested in fvtsaas, and CP4D gets installed with this change.

[patch] Cpd presync job needs to run in sync-job to ensure secrets are populated

---

root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml

Fixes an issue where the junit reporter name was being overused when two of the same configs are being created at the same time but at different scopes i.e. jdbc config at system and wsapp scope. The fixe is to add the scope to the reportername which gets used to create the resources.

[patch] fix junit reporter scope

---

instance-applications/130-ibm-mas-smtp-config/templates/02-ibm-mas_SmtpCfg.yaml

Renders new `smtp.disabled_templates` param into Suite SMTPCfg CR spec.
https://jsw.ibm.com/browse/MASCORE-5439
https://github.ibm.com/maximoappsuite/saas-tekton/pull/101
https://github.ibm.com/maximoappsuite/saas-deploy-py/pull/155
https://github.com/ibm-mas/cli/pull/1491
https://github.ibm.com/maximoappsuite/saas-envs-starter/pull/55
https://github.ibm.com/maximoappsuite/saas-task/pull/6
See https://github.ibm.com/maximoappsuite/saas-tekton/pull/101 for test results

[minor] Add support for SMTP disabledTemplates

---

root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml

Adds an ignore in Argo for the ManageWorkspace CR specs `mode` option that is part of the `deployment`. This allows the CR to be updated on the cluster so that the `mode` can be toggled between `up` and `down` without having to go via gitops and wait for Argo and the pipelines to pass through this change.
This mode is a state variable rather than a configuration variable and so we shouldn't keep state in gitops. This is the only change that will be allowed. If any other change is made to the CR then it will be reverted by Argo.
Tested in development env:
First with no mode at all in gitops:
Then with a mode present in gitops that is different to the live manifest:
In both cases there is no diff from argo, and argo keeps the live manifest as it is:

[minor] Add ignore for ManageWorkspace CR spec mode option

---

root-applications/ibm-mas-cluster-root/templates/099-instance-appset.yaml
root-applications/ibm-mas-instance-root/templates/000-ibm-sync-resources.yaml
root-applications/ibm-mas-instance-root/templates/010-ibm-sync-jobs.yaml
root-applications/ibm-mas-instance-root/templates/100-ibm-sls-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cp4d-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cp4d-operator-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-cs-control-app.yaml
root-applications/ibm-mas-instance-root/templates/110-ibm-db2u-app.yaml
root-applications/ibm-mas-instance-root/templates/120-db2-databases-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-spark-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-spss-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-wml-app.yaml
root-applications/ibm-mas-instance-root/templates/120-ibm-wsl-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-app.yaml
root-applications/ibm-mas-instance-root/templates/130-ibm-mas-suite-configs-app.yaml
root-applications/ibm-mas-instance-root/templates/200-ibm-mas-workspaces.yaml
root-applications/ibm-mas-instance-root/templates/500-ibm-mas-masapp-manage-install.yaml
root-applications/ibm-mas-instance-root/templates/510-550-ibm-mas-masapp-configs.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-assist-install.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-facilities-install.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-iot-install.yaml
root-applications/ibm-mas-instance-root/templates/510-ibm-mas-masapp-visualinspection-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-health-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-monitor-install.yaml
root-applications/ibm-mas-instance-root/templates/520-ibm-mas-masapp-optimizer-install.yaml
root-applications/ibm-mas-instance-root/templates/540-ibm-mas-masapp-predict-install.yaml
sub-charts/junitreporter/templates/00-presync-report-starter.yaml
sub-charts/junitreporter/templates/10-postsync-report-starter.yaml

Set the instance_id in the junit reporter for gitops so that devops_environment to be based on the instanceid rather than the clusterid. This allows different mas instances to report test results on a per instance level basis rather than per cluster, as per cluster would mean the test results of instance A would wipe over the test results of instance B.
Tested in fvtsaas as we know have test results per instance:

[patch] Set instance_id in junit reporter for gitops

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-verify.yaml

The Manage Foundation bundle is a new bundle that is deployed in all situations even if it is not set on the bundle CR spec. This means the test as it is fails as the spec doesn't match the status. This change is to drop the foundation bundle part and just check the other bundles. 
Tested in fvtsaas
Part of https://jsw.ibm.com/browse/MASCORE-5864

[patch] Fix Manage verify test for Manage Foundation

---

instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml

Issue: [MASCORE-6469](https://jsw.ibm.com/browse/MASCORE-6469)
1. SREs reported that if there was some other issue and the HADR setup job exited before starting the primary and standby HADR services, the job was retrying to take backup again and again even though earlier backups were successful - Hence we are checking if backup file is available (taking the timestamp from the log) and validating it was taken today, then we skip backup process and re-use this existing one. If not, we take backup
2. Copying the backup from Primary to Standby - we are checking if backup file is already available in standby. If available, we are validating the backup image using db2ckbkp command. If no error, we skip the copy process. If not, we copy the backup from primary to standby
3. DB2COMM value to be …

[patch] Fix bug with ReplicaDB post hadr setup job

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-sanity.yaml
instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-mvi-verify.yaml

The test records should contain the applicationid rather than a shorten version of it so that the FVT test can see it.
See https://jsw.ibm.com/browse/MASMVI-2285

[patch] Update the name of the mvi test records

---

instance-applications/600-ibm-post-sync-jobs/templates/001-ibm-create-initial-users.yaml
root-applications/ibm-mas-instance-root/templates/600-ibm-post-sync-jobs.yaml

After the automated initial user creation feature was merged to `gitops:main`  (https://github.com/ibm-mas/gitops/pull/278) an issue was discovered in fvtsaas where the new `postsyncjobs` ArgoCD application would fail to sync on MAS instances where Manage is not installed (which may be the case <9.1.x) due to the `mas-xxx-manage` namespace not being present.
This PR fixes this issue by only creating the Manage-related RBAC resources when Manage is actually installed.
```
Logging into AWS SecretsManager ...
Name                    Value             Type    Location
----                    -----             ----    --------
profile                <not set>             None    None
access_key     **************** shared-credentials-file
secret_key     **************** shared-credentials-file …
```

[patch] fix automated initial user creation when Manage is not installed

---

instance-applications/130-ibm-mas-smtp-config/templates/02-ibm-mas_SmtpCfg.yaml

Issue: [MASCORE-6185](https://jsw.ibm.com/browse/MASCORE-6185)
Provision to support for optional CA certificate for smtpcfg CR
Tested in noble4

[patch] Add smtpcfg certs to gitops

---

instance-applications/120-ibm-db2u-database/templates/03-db2uinstance.yaml
instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml

Issue: [MASCORE-7081](https://jsw.ibm.com/browse/MASCORE-7081)
After discussion with DBA team, following updates were made
1. Changes to restarting HADR command if restarting is done in an existing HADR environment
2. If auto backup is enabled, we use the latest backup if available and download it in standby pod
3. If auto backup is enabled but there is no backup (just an edge case if there are no backups in cos bucket), we take local backup and copy to cos bucket and then download it to standby
4. Some sleeps were added before starting or after starting HADR services
5. Removal of stop HADR in primary

[patch] Updates to HADR setup

---

cluster-applications/055-instana-agent-operator/templates/03-InstanaAgent.yaml

This PR introduces a toleration on the Instana agent that will allow the agent to be deployed on nodes that have a taint with key icp4data frequently used within our saas environments for nodes with exclusively DB2 workload.
Resolves MASCORE-7792
Testing
--------
tainted node with icp4data = xxxxx with NoSchedule.  Then deployed instana and validated that the instana agent was deployed on the node. 
Then ensured with the taint that applied to the node that the agent was still deployed.

[patch] Add toleration to instana agent pod

---

cluster-applications/053-falcon-operator/Chart.yaml
cluster-applications/053-falcon-operator/README.md
cluster-applications/053-falcon-operator/templates/01-OperatorGroup.yaml
cluster-applications/053-falcon-operator/templates/02-Subscription.yaml
cluster-applications/053-falcon-operator/templates/03-FalconNodeSensor.yaml
cluster-applications/053-falcon-operator/values.yaml
root-applications/ibm-mas-account-root/templates/000-cluster-appset.yaml
root-applications/ibm-mas-cluster-root/templates/053-falcon-operator-app.yaml

This is implementation for MASCORE-7805 - to add crowdstrike deployment back to the gitops pipelines. 
Testing
-------
**Validated the deployment of the CrowdStrike NodeSensor daemonset to the cluster, including nodes that are tainted.**
**Validated that all of the elements of the ArgoApp complete successfully**
**Validated the agent registered with IBM CS Portal**
**Validated that all containers started successfully **
** Validated successful pipeline execution **

[minor] re-add crowdstrike deploy back to mas deploy

---

cluster-applications/051-nvidia-gpu-operator/values.yaml

This change is to update nvidia versionndue to below error:
Bug: https://jsw.ibm.com/browse/MASCORE-7846

[patch] change default nvidia driver for gitops

---

instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml

Issue: [MASCORE-8236](https://jsw.ibm.com/browse/MASCORE-8236)
Currently, we are taking full backup every time. This is time consuming and we need to take backup only when the instance is provisioned for the first time. After that, only cron backups should be performed.

[patch] Postsync DB - Take full backup only during first provisioning

---

instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-add-label_Job.yaml

mas-app-route-sa is not able to list optimizerworkspaces
updated RBAC to allow service account to list and get optimizerworkspaces resource.
Error:
Wait for App workspaces to be ready and add label type=external to routes
Wait for App Workspaces to be ready
Error from server (Forbidden): optimizerworkspaces.apps.mas.ibm.com is forbidden: User "system:serviceaccount:mas-vta-test-optimizer:mas-app-route-sa" cannot list resource "optimizerworkspaces" in API group "apps.mas.ibm.com" in the namespace "mas-vta-test-optimizer"

[patch] add optimizerworkspaces resource to rbac

---

instance-applications/120-ibm-db2u-database/templates/10-postsync-setup-hadr.yaml

Issue: [MASCORE-8234](https://jsw.ibm.com/browse/MASCORE-8234)
1. Download of backup images from COS bucket are stuck indefinitely in MCSP Clusters. DBA team has confirmed that db2RemStgManager command has issues in MCSP Cluster alone either getting stuck or missing some bytes and has advised to use aws cli
2. Support for LOGARCHMETH1 in sdb pod as well

[patch] Post HADR setup script stuck in backup download

---

instance-applications/114-ibm-kmodels/templates/06-kmodel-watcher.yaml
instance-applications/114-ibm-kmodels/templates/07-kmodel-controller.yaml

Removed unwanted code as per the Ansible changes. The update was required in the staging environment due to a model training issue
Removed the code kmodel-watcher.yaml 
EXCLUDE_POD_NAMESPACES: "openshift-operators,openshift-pipelines"
WATCHER_SENDER_DELAY: "5"
EXCLUDE_JOB_NAMESPACES: "ibm-cpd"
CONTROLLER_URL: "https://km-controller:8443"
Removed the code kmodel-controller.yaml
CONNECTOR_TTL: "10"
CONNECTOR_DEFAULT_TAG: "{{ .Values.mas_aibroker_connector_tag }}"
Need to update with value "1.0.4" PIPELINE_DEFAULT_STEP_TAG

[minor] Removed and update Kmodel Role

---

instance-applications/010-ibm-sync-jobs/templates/00-aws-docdb-add-user_Job.yaml

Issue: [MASCORE-9478](https://jsw.ibm.com/browse/MASCORE-9478)
oc secret sls-mongo-credentials was created initially with the values from aws secret but the aws secret got changed again which led to mismatch and SREs had to do hard refresh again
When sync retry of instance.<clusterid>.<instancename> argo app happens because any of other argo apps failed for some reason, the retry of aws-docdb-add-user job **regenerated** the docdb instance password again since it was trying to read from the oc secret value which hasn't been updated (ie. It gets updated after a hard refresh later though)
Instead of reading from oc secret which may contain outdated value, we directly read from AWS secrers manager for the latest value and hence avoid the credential to be regenerated
Tested in mcspkvn4 by …

[patch] Mongo secret creation/updation trigger twice.
